### ISSUE TITLE
Installing prereqs gives error

### ISSUE THREAD

**Issue by rdkgit** [mkrupczak3/OpenAthena#22]
python3 -m pip install -r requirements.txt

......................

Using legacy 'setup.py install' for matplotlib, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pillow, since package 'wheel' is not installed.
Using legacy 'setup.py install' for imagecodecs, since package 'wheel' is not installed.
Building wheels for collected packages: mgrs
  Building wheel for mgrs (pyproject.toml) ... done
  Created wheel for mgrs: filename=mgrs-1.4.5-cp311-cp311-linux_x86_64.whl size=51702 sha256=cd36d18e6997c41c4249d095f9304d1fb93cd888a3ca39c01a5501bd87a2c8c7
  Stored in directory: /tmp/pip-ephem-wheel-cache-2bpcj0r2/wheels/5b/92/1d/bc202481fdffa49ca25be0127b71436204b80482e03e80878b
Successfully built mgrs
Installing collected packages: pillow, imagecodecs, fasteners, entrypoints, certifi, pyproj, numcodecs, mgrs, matplotlib, zarr, geotiff
  Running setup.py install for pillow ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pillow did not run successfully.
  │ exit code: 1
  ╰─> [192 lines of output]
      running install
      /usr/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(

      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/features.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_version.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_util.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_binary.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__main__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__init__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Image.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-yire0dg_/pillow_dca1cd4b200c4f9198ae27ba6dc01a2e/setup.py", line 989, in <module>
          setup(
        File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 690, in run
          self.run_command('build')
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/tmp/pip-install-yire0dg_/pillow_dca1cd4b200c4f9198ae27ba6dc01a2e/setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yire0dg_/pillow_dca1cd4b200c4f9198ae27ba6dc01a2e/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pillow

**Comment by rdkgit** [comment]
pip3 --version
pip 22.2.2 from /usr/lib/python3.11/site-packages/pip (python 3.11)

python --version
Python 3.11.1

Fedora release 37 (Thirty Seven)
Linux xxx 6.1.6-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 14 16:55:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rdkgit** [comment]
Tried pip3 cache purge but still get error installing pillow

**Comment by mkrupczak3** [comment]
@rdkgit  try `python -m pip install --upgrade pip`

Does this install work correctly thereafter? To ensure consistency, run:

`python -m pip install -r requirements.txt`

**Comment by mkrupczak3** [comment]
Closed due to inactivity. This appears to be a rare issue related to Python installation
